# Generated by Django 4.0 on 2022-11-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationTag',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('issuer', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationTag',
            fields=[
                ('school_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceTag',
            fields=[
                ('job_title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('tasks', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='auth.user')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refers', to='auth.user')),
                ('referer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('bio', models.TextField(null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('followers_count', models.IntegerField(blank=True, default=0, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('certifications', models.ManyToManyField(blank=True, related_name='licenses', to='users.CertificationTag')),
                ('connections', models.ManyToManyField(related_name='connection', to=settings.AUTH_USER_MODEL)),
                ('education', models.ManyToManyField(blank=True, related_name='schools', to='users.EducationTag')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('interests', models.ManyToManyField(blank=True, related_name='topic_interests', to='users.InterestTag')),
                ('jobs', models.ManyToManyField(blank=True, related_name='jobs_done', to='users.ExperienceTag')),
                ('skills', models.ManyToManyField(blank=True, related_name='personal_skills', to='users.SkillTag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='auth.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Connections',
            },
        ),
    ]
