# Generated by Django 4.0 on 2023-07-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrefer',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Referrals'},
        ),
        migrations.RemoveField(
            model_name='userrefer',
            name='caption',
        ),
        migrations.AlterField(
            model_name='userrefer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
