# Generated by Django 4.0 on 2024-03-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userrefer_options_remove_userrefer_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='certifications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='users.certificationtag'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='users.educationtag'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='topic_interests', to='users.interesttag'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='jobs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jobs',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_done', to='users.experiencetag'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personal_skills', to='users.skilltag'),
            preserve_default=False,
        ),
    ]
