# Generated by Django 4.0 on 2021-12-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210517_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationTag',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('issuer', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationTag',
            fields=[
                ('school_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceTag',
            fields=[
                ('job_title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('tasks', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='users.CertificationTag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='schools', to='users.EducationTag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='jobs_done', to='users.ExperienceTag'),
        ),
    ]
