# Generated by Django 4.0 on 2022-01-28 08:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('discussion', '0003_discussion_tags'),
        ('users', '0005_certificationtag_educationtag_experiencetag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicTag',
            new_name='InterestTag',
        ),
    ]
