# Generated by Django 4.0 on 2022-02-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userrefer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrefer',
            options={'verbose_name_plural': 'Referrals'},
        ),
    ]
