# Generated by Django 4.0 on 2022-04-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0012_remove_userprofile_connections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='from_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='auth.user'),
        ),
    ]
