# Generated by Django 4.0 on 2022-04-06 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_alter_connectionrequest_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='connections',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='connections',
            field=models.ManyToManyField(null=True, related_name='connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
