# Generated by Django 4.0 on 2022-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='mumble',
            new_name='feed',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('feed', 'feed'), ('discussion', 'discussion'), ('follow', 'follow')], max_length=20),
        ),
    ]
