# Generated by Django 4.0 on 2021-12-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_mumble_parent_remove_mumble_remumble_and_more'),
        ('notification', '0005_auto_20210610_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mumble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feed'),
        ),
    ]
