# Generated by Django 4.0 on 2022-01-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MumbleVote',
            new_name='FeedLike',
        ),
    ]
