# Generated by Django 4.0 on 2022-12-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_rename_mumblevote_feedlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedlike',
            old_name='mumble',
            new_name='feed',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='remumble',
        ),
        migrations.AddField(
            model_name='feed',
            name='refeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refeeds', to='feed.feed'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='feed_user', through='feed.FeedLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
