# Generated by Django 4.0 on 2021-12-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_mumble'),
        ('feed', '0003_remove_mumble_parent_remove_mumble_remumble_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mumble',
        ),
    ]
